### ISSUE TITLE
getAccessToken not working on Cloudflare Workers

### ISSUE THREAD

**Issue by oriollpz** [kriasoft/web-auth-library#28]
The function

```
const accessToken = await getAccessToken({
      credentials: credentials,
      scope: "https://www.googleapis.com/auth/cloud-platform",
      waitUntil: c.executionCtx.waitUntil,
});
```

Isn't working for me, it works locally, but when I use it in the worker it says this: **TypeError: Illegal invocation**

Anyone faced the same problem?

**Comment by zewelor** [comment]
I have the same problem, did you solve it ?

**Comment by oriollpz** [comment]
@zewelor I stopped using this library and I used [this](https://github.com/kriasoft/web-auth-library) instead.

**Comment by zewelor** [comment]
> @zewelor I stopped using this library and I used [this](https://github.com/kriasoft/web-auth-library) instead.

Hmm i see link to this ( web-auth-library ) library

**Comment by Manouchehri** [comment]
Same issue here.

**Comment by Manouchehri** [comment]
Use `waitUntil: ctx.waitUntil.bind(ctx)` instead.

**Comment by RickYangzz** [comment]
> Use `waitUntil: ctx.waitUntil.bind(ctx)` instead.

but I got '{}' from my firestore.

**Comment by RickYangzz** [comment]
<img width="1092" alt="image" src="https://github.com/user-attachments/assets/e35799bb-7f08-4350-8f37-acecd63d7b6e">
Thanks everybody below this problem. I have been successful. This is my code.

**Comment by lord5et** [comment]
I tried it today and I'm getting following info:
```
TypeError: Illegal invocation: function called with incorrect `this` reference. See https://developers.cloudflare.com/workers/observability/errors/#illegal-invocation-errors for details.
A ReadableStream branch was created but never consumed. Such branches can be created, for instance, by calling the tee() method on a ReadableStream, or by calling the clone() method on a Request or Response object. If a branch is created but never consumed, it can force the runtime to buffer the entire body of the stream in memory, which may cause the Worker to exceed its memory limit and be terminated. To avoid this, ensure that all branches created are consumed.

 * Unused stream created:
    at null.<anonymous> (file:///C:/projects/parcels-api/node_modules/web-auth-library/dist/google/accessToken.js:105:36)
    at async getAccessToken (file:///C:/projects/parcels-api/node_modules/web-auth-library/dist/google/accessToken.js:127:12)
    at async getFirebaseToken (file:///C:/projects/parcels-api/src/utils/firebase-auth.ts:21:23)
    at async getAuthHeaders (file:///C:/projects/parcels-api/src/clients/firestore-client.ts:8:17)
    at async getUserAvailableCoverage (file:///C:/projects/parcels-api/src/clients/firestore-client.ts:17:19)
    at null.<anonymous> (async file:///C:/projects/parcels-api/.wrangler/tmp/dev-RVTltV/index.js:39419:38)
    at async dispatch (file:///C:/projects/parcels-api/node_modules/hono/dist/compose.js:29:17)
    at async cors2 (file:///C:/projects/parcels-api/node_modules/hono/dist/middleware/cors/index.js:65:5)
    at async dispatch (file:///C:/projects/parcels-api/node_modules/hono/dist/compose.js:29:17)
    at async poweredBy2 (file:///C:/projects/parcels-api/node_modules/hono/dist/middleware/powered-by/index.js:4:5)
```

**Comment by auniverseaway** [comment]
@arekgotfryd I had the same issue when using CF Workers without `hono` and `executionCtx`.

Here's how I ended up solving...

```js
return getAccessToken({
    credentials: env.GOOGLE_CLOUD_CREDENTIALS,
    scope: 'https://www.googleapis.com/auth/cloud-translation',
    waitUntil: ctx.waitUntil.bind(ctx),
    env,
  });
```
Note how the `waitUntil` function is re-bound to (CF Worker native) ctx.

**Comment by niklasfjeldberg** [comment]
> <img alt="image" width="1092" src="https://private-user-images.githubusercontent.com/38999212/349897636-e35799bb-7f08-4350-8f37-acecd63d7b6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NDk5OTUsIm5iZiI6MTczMjU0OTY5NSwicGF0aCI6Ii8zODk5OTIxMi8zNDk4OTc2MzYtZTM1Nzk5YmItN2YwOC00MzUwLThmMzctYWNlY2Q2M2Q3YjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDE1NDgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMGE4Y2EyMDZlOWEwZGU1NmYxYzg3YTgzZWUyNWNjMWViMmU3N2U3NzU0YWY2NGQ5YThjNWRmMzExOGU0ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L6OHQ5cuAcYg6gewUA_3DeOOnupTSrNpv4DATPmZq2s"> Thanks everybody below this problem. I have been successful. This is my code.

This worked for me, thanks!
